### ISSUE TITLE
FPtaylor api fetch calls are not working

### ISSUE THREAD

**Issue by parthrdesai** [herbie-fp/odyssey#95] opened 2024-08-21 17:22 UTC
![1](https://github.com/user-attachments/assets/8d50a719-cc37-4de9-9479-c849a278f713)
![2](https://github.com/user-attachments/assets/79993ad8-4ef4-4a95-8361-7f6471427629)
![3](https://github.com/user-attachments/assets/a4f2db6e-7cbe-488f-bc7e-b903e2d1070c)

When I do a fetch request for fptaylor analysis it just stays pending and doesn't end and give any response. There's the same error in the old code which was in main, so I think there's some issue with endpoint

**Comment by elmisback** [comment] 2024-08-22 23:29
Linux is the only platform where FPBench/Taylor calls currently work locally out of the box. You have to run your own server for this if you want to test it. The Odyssey web demo should be working...
![image](https://github.com/user-attachments/assets/9e7bcfd8-dcf5-4e17-8ba2-5dbb8feb9185)
...but it's not, there's some kind of CORS issue there.

**Comment by elmisback** [comment] 2024-08-22 23:30
@parthrdesai were you testing this with the WSL/Linux VSCode extension?

**Comment by elmisback** [comment] 2024-08-22 23:30
If you were on Mac/Windows, we can close this. I'll add an issue for the CORS error

**Comment by elmisback** [comment] 2024-08-26 06:35
I confirmed that these work against a local server. I think this is a CORS error due to the FPBench server exec endpoint having fallen over. We probably need some kind of /up test against those endpoints.

**Closed by elmisback** 2024-08-26 06:35 UTC
